<?php

/**
 * @file go1_dev.module
 */

use Drupal\at_base\Hook\Entity\View_Alter as Entity_View_Alter;

/**
 * Implementation of hook_entity_view_alter
 * Support to alter entity (block, node,...)
 */
function go1_dev_entity_view_alter(&$build, $entity_type) {
  at_id(new Drupal\at_base\Hook\Entity\View_Alter($build, $entity_type))->execute();
}

/**
 * Add a trim function
 */
function go1_dev_trim_words($string, $words){
  $string = explode(' ', $string);
  if (count($string) > $words) {
    return implode(' ', array_slice($string, 0, $words)) . '...';
  }
  return implode(' ', $string);
}
